TodoListView implemented for Todo app along with user authorisation check and data filtering
ankush-velotio/learndjango pull request #3
Opened 2021-08-16 10:19 UTC by ankush-velotio

Implemented features:
1. Created data model for Todo app.
2. Implemented TodoListView for the Todo app that will show the Todo list.
3. Implemented user authorisation check for the TodoListView that will check if the user is authorised before showing the data.
4. Implemented data filtering that will show only those Todo's to the user for which either user is the owner or the user is an editor.

2021-08-16 10:46 UTC, ronakmutha commented on server/requirements/requirements.txt
> +django-model-utils==4.1.1
Why do you require this?

2021-08-16 12:02 UTC, ronakmutha requested changes

2021-08-16 12:02 UTC, ronakmutha commented on server/requirements/requirements.txt
> +django-timestampedmodel==0.1.0
Why do you require these libraries?

2021-08-16 12:02 UTC, ronakmutha commented on server/apps/todo/models.py
> +    )
Editors are actual users, you can use Many to Many field here

2021-08-16 12:02 UTC, ronakmutha commented on server/apps/todo/migrations/0005_alter_todo_date.py
> +    ]
Merge the migrations into one!

2021-08-16 12:02 UTC, ronakmutha commented on server/apps/todo/views.py
> +        user = User.objects.filter(id=payload['id']).first()
You can use `get` here, rather than first

2021-08-16 12:02 UTC, ronakmutha commented on server/apps/todo/models.py
> +    updated_by = models.CharField(max_length=100, blank=True, null=True)
Write an abstract model. Check the pure drive code!

2021-08-16 12:20 UTC, ankush-velotio commented on server/requirements/requirements.txt
> +django-timestampedmodel==0.1.0
I'm using `django-model-utils` to get `Choices` function that is used to set choices for status field in `todo/models.py`.

Using `django-timestampedmodel` to get TimestampedModel for implementing `Todo` model in `todo/models.py`. TimestampedModel will provide created_at and updated_at fields by default.

I just found another way to do this:
`
class MyModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
`
I will remove the `django-timestampedmodel` and implement the same using above snippet

2021-08-16 12:41 UTC, ankush-velotio commented on server/apps/todo/migrations/0005_alter_todo_date.py
> +    ]
Squashed migrations in new commit

2021-08-16 12:48 UTC, ankush-velotio commented on server/apps/todo/views.py
> +        user = User.objects.filter(id=payload['id']).first()
Updated

2021-08-17 05:59 UTC, ankush-velotio commented on server/apps/todo/models.py
> +    )
Updated with ManyToManyField type in latest commit

2021-08-17 06:23 UTC, ankush-velotio commented on server/apps/todo/models.py
> +    updated_by = models.CharField(max_length=100, blank=True, null=True)
Implemented abstract models in latest commit

2021-08-17 06:32 UTC, ankush-velotio commented on server/requirements/requirements.txt
> +django-timestampedmodel==0.1.0
I have removed `django-timestampedmodel` dependecy and implemented the same behaviour by implementing `TimestampedModel` abstract model.

2021-08-19 04:33 UTC, ankush-velotio commented
PR #4 is an extension of PR #3 . So, closing PR #3 unmerged.

2021-08-19 04:33 UTC, closed without merging